import './DailyQuote.css';

const quotes: { text: string; author: string }[] = [
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Keep your face always toward the sunshine and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
  { text: "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", author: "Helen Keller" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
  { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { text: "What we think, we become.", author: "Buddha" },
  { text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Whoever is happy will make others happy too.", author: "Anne Frank" },
  { text: "The greatest wealth is to live content with little.", author: "Plato" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney" },
  { text: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { text: "Gratitude turns what we have into enough.", author: "Melody Beattie" },
  { text: "Joy is not in things; it is in us.", author: "Richard Wagner" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "Love the life you live. Live the life you love.", author: "Bob Marley" },
  { text: "Every moment is a fresh beginning.", author: "T.S. Eliot" },
  { text: "The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.", author: "Charles Dickens" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Waldo Emerson" },
  { text: "We must be willing to let go of the life we planned so as to have the life that is waiting for us.", author: "Joseph Campbell" },
  { text: "What a wonderful thought it is that some of the best days of our lives haven't even happened yet.", author: "Anne Frank" },
  { text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson" },
  { text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King Jr." },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Family is not an important thing. It's everything.", author: "Michael J. Fox" },
  { text: "Home is the nicest word there is.", author: "Laura Ingalls Wilder" },
  { text: "In family life, love is the oil that eases friction, the cement that binds closer together.", author: "Friedrich Nietzsche" },
  { text: "The love of a family is life's greatest blessing.", author: "Eva Burrows" },
  { text: "Other things may change us, but we start and end with family.", author: "Anthony Brandt" },
  { text: "A positive attitude causes a chain reaction of positive thoughts, events, and outcomes.", author: "Wade Boggs" },
  { text: "You will never have this day again, so make it count.", author: "Unknown" },
  { text: "Every day may not be good, but there is something good in every day.", author: "Alice Morse Earle" },
  { text: "The more you praise and celebrate your life, the more there is in life to celebrate.", author: "Oprah Winfrey" },
  { text: "Enjoy the little things, for one day you may look back and realize they were the big things.", author: "Robert Brault" },
  { text: "You are enough just as you are.", author: "Meghan Markle" },
  { text: "Laughter is timeless, imagination has no age, and dreams are forever.", author: "Walt Disney" },
  { text: "The most wasted of days is one without laughter.", author: "E.E. Cummings" },
  { text: "Happiness is a warm puppy.", author: "Charles M. Schulz" },
  { text: "In every walk with nature, one receives far more than he seeks.", author: "John Muir" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Not all who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
  { text: "The earth has music for those who listen.", author: "William Shakespeare" },
  { text: "We don't stop playing because we grow old; we grow old because we stop playing.", author: "George Bernard Shaw" },
  { text: "Do small things with great love.", author: "Mother Teresa" },
  { text: "The greatest thing you'll ever learn is just to love and be loved in return.", author: "Eden Ahbez" },
  { text: "Let us always meet each other with smile, for the smile is the beginning of love.", author: "Mother Teresa" },
  { text: "A happy family is but an earlier heaven.", author: "George Bernard Shaw" },
  { text: "The best things in life are the people you love, the places you've been, and the memories you've made along the way.", author: "Unknown" },
];

function getDailyQuote(): { text: string; author: string } {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return quotes[dayOfYear % quotes.length];
}

export function DailyQuote() {
  const quote = getDailyQuote();

  return (
    <div className="daily-quote">
      <div className="daily-quote-text">"{quote.text}"</div>
      <div className="daily-quote-author">— {quote.author}</div>
    </div>
  );
}
